# Agilepy engineering API

In [1]:
import os
from pathlib import Path
from shutil import rmtree

In [2]:
outDir = Path(os.environ["AGILE"]).joinpath( Path("agilepy-test-data/unittesting-output/jupyter/") )

if outDir.exists() and outDir.is_dir():
    print("Removing",outDir)
    rmtree(outDir)

In [3]:
from agilepy.api.AGEng import AGEng

In [4]:
agEng = AGEng("./config_file.yaml")

2020-02-11 16:04:04,843 [INFO    ] [AgilepyLogger] File and Console loggers are active. Log file: /opt/anaconda3/envs/agilepy/agiletools/agilepy-test-data/unittesting-output/jupyter/eng_data/logs/quickstart_20200211-160404.log
2020-02-11 16:04:04,843 [INFO    ] [PlottingUtils] Plot configuration: 'standard'. fig_width_pt: 426.791340 fontsize:10.000000


In [5]:
agEng.config.printOptions("plotting")

{'twocolumns': False}


In [6]:
%matplotlib notebook

In [7]:
src_x=129.7
src_y=3.7
ref="gal"
zmax=60
step=10
logfilesIndex=None
computeHistogram=True
writeFiles=True
saveImage=True
formatExt="png"
title="Visibility plot 184075134 - 184275134"
tmin = 456384273
tmax = 459426294

In [8]:
plot = agEng.visibilityPlot(tmin, tmax, src_x, src_y, ref, zmax, step, computeHistogram, writeFiles, logfilesIndex, saveImage, formatExt, title)

2020-02-11 16:04:04,861 [INFO    ] [AGEng] Computing pointing distances from source (129.700000, 3.700000) gal in [456384273.000000, 459426294.000000]
2020-02-11 16:04:04,865 [INFO    ] [AGEng] 44 log files satisfy the interval 456384273.000000-459426294.000000
2020-02-11 16:04:04,866 [INFO    ] [AGEng] Computing pointing distances. Please wait..
2020-02-11 16:04:04,866 [INFO    ] [AGEng] 1/44 $AGILE/agilepy-test-data/log_data/agql1806180525_1806180625.LOG.gz
2020-02-11 16:04:04,960 [INFO    ] [AGEng] 2/44 $AGILE/agilepy-test-data/log_data/agql1806180625_1806180733.LOG.gz
2020-02-11 16:04:05,055 [INFO    ] [AGEng] 3/44 $AGILE/agilepy-test-data/log_data/agql1806180733_1806180833.LOG.gz
2020-02-11 16:04:05,142 [INFO    ] [AGEng] 4/44 $AGILE/agilepy-test-data/log_data/agql1806180833_1806180920.LOG.gz
2020-02-11 16:04:05,214 [INFO    ] [AGEng] 5/44 $AGILE/agilepy-test-data/log_data/agql1806180920_1806181020.LOG.gz
2020-02-11 16:04:05,298 [INFO    ] [AGEng] 6/44 $AGILE/agilepy-test-data/log

<IPython.core.display.Javascript object>

2020-02-11 16:04:17,656 [INFO    ] [PlottingUtils] Visibility plot at: /opt/anaconda3/envs/agilepy/agiletools/agilepy-test-data/unittesting-output/jupyter/eng_data/agile_visibility_ra29.462233770913944_dec65.69530751575293_tstart456384273.0_tstop456541544.1_zmax60step10.png
2020-02-11 16:04:17,810 [INFO    ] [PlottingUtils] Plot configuration: 'standard'. fig_width_pt: 426.791340 fontsize:10.000000




**** DELTA1:  0.10000002384185791
[    0     0     0 15224 17242 12921 12211 11247]


<IPython.core.display.Javascript object>

2020-02-11 16:04:23,157 [INFO    ] [PlottingUtils] Visibility histogram at: /opt/anaconda3/envs/agilepy/agiletools/agilepy-test-data/unittesting-output/jupyter/eng_data/agile_histogram_ra29.462233770913944_dec65.69530751575293_tstart456384273.0_tstop456541544.1_zmax60step10.png


/opt/anaconda3/envs/agilepy/lib/python3.7/site-packages/agilepy/utils/PlottingUtils.py:226: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  ax2 = f2.add_subplot(111)


In [9]:
separations, ti_tt, tf_tt, ti_mjd, tf_mjd, src_ra, src_dec = agEng._computePointingDistancesFromSource(tmin, tmax, src_x, src_y, ref, zmax, step, writeFiles, logfilesIndex)

2020-02-11 16:04:23,164 [INFO    ] [AGEng] Computing pointing distances from source (129.700000, 3.700000) gal in [456384273.000000, 459426294.000000]
2020-02-11 16:04:23,170 [INFO    ] [AGEng] 44 log files satisfy the interval 456384273.000000-459426294.000000
2020-02-11 16:04:23,170 [INFO    ] [AGEng] Computing pointing distances. Please wait..
2020-02-11 16:04:23,171 [INFO    ] [AGEng] 1/44 $AGILE/agilepy-test-data/log_data/agql1806180525_1806180625.LOG.gz
2020-02-11 16:04:23,267 [INFO    ] [AGEng] 2/44 $AGILE/agilepy-test-data/log_data/agql1806180625_1806180733.LOG.gz
2020-02-11 16:04:23,371 [INFO    ] [AGEng] 3/44 $AGILE/agilepy-test-data/log_data/agql1806180733_1806180833.LOG.gz
2020-02-11 16:04:23,456 [INFO    ] [AGEng] 4/44 $AGILE/agilepy-test-data/log_data/agql1806180833_1806180920.LOG.gz
2020-02-11 16:04:23,526 [INFO    ] [AGEng] 5/44 $AGILE/agilepy-test-data/log_data/agql1806180920_1806181020.LOG.gz
2020-02-11 16:04:23,610 [INFO    ] [AGEng] 6/44 $AGILE/agilepy-test-data/log

In [10]:
import matplotlib.pyplot as plt
separations = [s.value for s in separations]
h,b,p = plt.hist(separations,bins=[0, 10, 20, 30, 40, 50, 60, 70, 80, 180], density=False)
plt.show()

In [11]:
import numpy as np
h

array([    0.,     0.,     0., 15224., 17242., 12921., 12211., 11247.,
       88427.])

In [12]:
[    0     0     0 15224 17242 12921 12211 11247]

SyntaxError: invalid syntax (<ipython-input-12-5d87b9167f57>, line 1)